aliases: []
creation_timestamp: 1711701581995
current_stage: None
description: ''
last_updated_timestamp: 1711701581995
name: Sentiment_Analysis_experimentation
run_id: d57c86e9ee1246b8aa3afdab7e00d596
run_link: ''
source: file:///C:/Users/banav/Desktop/INTERNSHIP/ml_flow/mlruns/741706321559237835/d57c86e9ee1246b8aa3afdab7e00d596/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///C:/Users/banav/Desktop/INTERNSHIP/ml_flow/mlruns/741706321559237835/d57c86e9ee1246b8aa3afdab7e00d596/artifacts/best_estimator
user_id: null
version: 1
